# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 010708b269a4ee8bc464807df6097b369cc305361b8a0fe4232aad6266c18c3cb227a03e51f1d914f9902e735cb9fa0fa1c853c7b7adcdbeefa0f5cbb0bfdb1a

test:
  secret_key_base: 9b031f0ce107a18d8c9fa3c8078a57002943efac7accd52635dc715c814c52c4acc82d0cbfcc6bbe6c629c6e5f2f871ab4ad0c2e32f3157e33f11a32ce1de36a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
